run:
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errorlint
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goprintffuncname
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - prealloc
    - predeclared
    - thelper
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 8
  funlen:
    lines: 150
    statements: 80
